#STORED PROCEDURE PARA REALIZAR OPERACIONES EN LA TABLA courses

#STORED PROCEDURE PARA CONSULTAR TODOS LOS REGISTROS
DELIMITER $$
	CREATE PROCEDURE select_courses()
    BEGIN
		SELECT id, name, description FROM courses;
    END$$
DELIMITER $$

#STORED PROCEDURE PARA INSERTAR UN NUEVO REGISTRO
DELIMITER $$
	CREATE PROCEDURE insert_courses(
		IN _ID VARCHAR(10),
        IN _NAME VARCHAR(100),
        IN _DESCRIPTION VARCHAR(250)
    )
    BEGIN
		INSERT INTO courses(id, name, description) VALUES(_ID, _NAME, _DESCRIPTION);
    END$$
DELIMITER $$

#STORED PROCEDURE PARA CONSULTAR UN REGISTRO CON SU ID
DELIMITER $$
	CREATE PROCEDURE select_courses_id(
		IN _ID VARCHAR(10)
    )
    BEGIN
		SELECT id, name, description FROM courses WHERE id = _ID;
    END$$
DELIMITER $$